### PR TITLE
fix(insert): make insert open and objc

### PR DESCRIPTION
**Pull request by harish-fueled**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
@harish-fueled I'd make all the methods open to customisation

**Comment by Vadim-Yelagin** [comment]
Overriding extension methods is not a good idea.
You have other options here: add your adapter class than implements `DataChangeTarget` in any custom way by calling to a table view (you might need to extend `TableViewDataSource` in that case); or subclass UITableView and override `.insertRows(at:, with:)`.

**Comment by harish-fueled** [comment]
We can't subclass UITableView and override .insertRows(at:, with:). as the methods have been declared in an extension and we can't override those yet. to override them i pushed this pr. please help and let us know if we can do it some other way.

**Comment by Vadim-Yelagin** [comment]
That's the idea if you can't subclass your table view:
```
struct CustomTableViewChangeTargetAdapter: DataChangeTarget {
    let tableView: UITableView

    func ds_performBatchChanges(_ batchChanges: @escaping () -> ()) {
        // call default implementation
        tableView.ds_performBatchChanges(batchChanges)
    }
    func ds_deleteItems(at indexPaths: [IndexPath]) {
        tableView.ds_deleteItems(at: indexPaths)
    }
    // ...
    func ds_insertItems(at indexPaths: [IndexPath]) {
        // do something custom
        for indexPath in indexPaths {
            if (indexPath.row % 2) == 0 {
                tableView.insertRows(at: [indexPath], with: .left)
            } else {
                tableView.insertRows(at: [indexPath], with: .right)
            }
        }
    }
    // ...
}

// what you had with default fade animations
change.apply(to: self.tableView)
// what you can do now for custom insert animations
change.apply(to: CustomTableViewChangeTargetAdapter(tableView: self.tableView))
```

**Comment by harish-fueled** [comment]
Thanks a lot Vadim, Really appreciate you helping out :) :)

**Pull request closed without merging**
