### PR TITLE
feat(data-change-target): make castomizable dataChangeTargets for  Ta…

### PR DESCRIPTION
**Pull request by heymansmile**
…bleViewDataSource and CollectionViewDataSource.

### CODE REVIEW

**Comment by Vadim-Yelagin** [comment]
This can cause hard-to-find bugs in existing code that changes the value of `tableView` outlet on `TableViewDataSource` instance after it had already been in use: cached value of `dataChangeTarget` will continue referencing the old table view.
Also I don't see any need for removing `extension UITableView: DataChangeTarget` and forcing existing code to migrate to the new `TableViewChangeTarget` adapter.
I suggest you achieve the flexibility you need by simply adding a plain `public final var dataChangeTarget: DataChangeTarget? = nil` and then essentially doing `change.apply(to: dataChangeTarget ?? tableView)`.
That way, all existing code will continue to work as it was until you actually use this new feature by explicity setting a custom `dataChangeTarget`.
Same naturally applies to collections views as well.

**Comment by heymansmile** [comment]
It makes sense @Vadim-Yelagin, thanks! Will do the changes.

**Comment by Vadim-Yelagin** [comment]
I think that'd be a bit better:
```
if let this = self, let dataChangeTarget = this.dataChangeTarget ?? this.tableView {
    change.apply(to: dataChangeTarget)
}
```

**Comment by heymansmile** [comment]
👍

**Pull request merged**
